---
# Role: apache
# roles/apache/tasks/main.yml
#
# Installs Apache plus Passenger
#
# Usage:
#    - { role: apache, passenger_ver: *required* }
#
# NOTE: this role does not configure an application Virtual Host, you must do that in an application setup role

- name: determine system gem path
  shell: 'gem env gemdir'
  register: system_gem_path

- name: install passenger gem
  become: yes
  gem: name=passenger user_install=no state=present version={{ passenger_ver }}

- name: install apache packages for Ubuntu 16
  become: yes
  package: name={{ item }} state=present
  with_items:
    - apache2
    # if this is omitted, passenger doesn't have the headers it needs
    - libaprutil1-dev
    - apache2-dev

- name: install passenger-install-apache2-module
  become: yes
  shell: passenger-install-apache2-module --auto creates={{ system_gem_path.stdout }}/gems/passenger-{{ passenger_ver }}/buildout/apache2/mod_passenger.so

- name: generate passenger.conf file
  become: yes
  shell: bash -c "passenger-install-apache2-module --snippet > /etc/apache2/conf-enabled/passenger.conf" creates=/etc/apache2/conf-enabled/passenger.conf

- name: configure passenger.conf to accept encoded slashes
  become: yes
  lineinfile:
    dest: /etc/apache2/conf-enabled/passenger.conf
    state: present
    line: PassengerAllowEncodedSlashes on
    insertbefore: </IfModule>

- name: remove default apache site
  become: yes
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: enable rewrite module
  become: yes
  command: a2enmod rewrite
