---
- name: remove package imagemagick
  become: yes
  package: name=imagemagick state=absent

- name: install IM dependencies
  become: yes
  package: name={{ item }} state=present
  with_items:
    - cmake

- name: create IM sources dir
  become: yes
  file: owner={{ ansible_ssh_user }} state=directory path=imagemagick_sources

- name: IM add ldconfig for /usr/local/lib
  become: yes
  copy: dest=/etc/ld.so.conf.d/usr-local.conf content=/usr/local/lib owner=root group=root mode=0644
