---
# ROLE: imagemagick
# roles/imagemagick/tasks/main.yml
#
# USAGE:
# Installs a specified version of ImageMagick. Note there are specific versions
# of supporting libraries tested to work with Samvera PDF derivatives.
#   Known good version combo:
# - { role: imagemagick, imagemagick_version: '7.0.7', openjpg_ver: '2.1.0', libtiff_ver: '4.0.5', libpng_ver: '1.6.28', gs_ver: '9.19' }
#
# NOTE: you may supply either a fully specificed IM version with patchlevel, or omit the patchlevel.
#       If the patchlevel is omitted, the system will install the most recent available patch for the specified version number.

- name: install imagemagick specific dependencies
  import_tasks: im_libraries.yml

- name: build openjpg
  import_tasks: openjpg.yml

- name: build libtiff
  import_tasks: libtiff.yml

- name: build libpng
  import_tasks: libpng.yml

- name: build ghostscript
  import_tasks: ghostscript.yml

- name: build imagemagick
  import_tasks: imagemagick.yml
