---
# ROLE: packages
# roles/pip/tasks/main.yml
#
# installs pip - required for python packages

- name: install python tools
  package: name={{ item }} state=present
  become: yes
  with_items:
    - python-setuptools
    - python-dev
    - build-essential
    - python-pip

# - name: install pip
#   become: yes
#   easy_install:
#     name: pip
#     state: latest
#
- name: install pexpect for interactive commands
  become: yes
  pip:
    name: pexpect
